// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHv4-kHPypUigXHn9dvZrHgrQJaZIz9iE',
    appId: '1:836519579068:web:5dc2d9404b5ad3589fafb9',
    messagingSenderId: '836519579068',
    projectId: 'ecommerce-5ae51',
    authDomain: 'ecommerce-5ae51.firebaseapp.com',
    storageBucket: 'ecommerce-5ae51.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnDha73sa2FmGmbiugrdqCnGrVFd_xuqg',
    appId: '1:836519579068:android:e8338f66d8a138b29fafb9',
    messagingSenderId: '836519579068',
    projectId: 'ecommerce-5ae51',
    storageBucket: 'ecommerce-5ae51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1cwnTFwnaZxPuicZho5DiB-FDlGPOtF4',
    appId: '1:836519579068:ios:826bf09fad8243ce9fafb9',
    messagingSenderId: '836519579068',
    projectId: 'ecommerce-5ae51',
    storageBucket: 'ecommerce-5ae51.firebasestorage.app',
    iosBundleId: 'com.adminfoodi1.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1cwnTFwnaZxPuicZho5DiB-FDlGPOtF4',
    appId: '1:836519579068:ios:fac2c431ad2716b49fafb9',
    messagingSenderId: '836519579068',
    projectId: 'ecommerce-5ae51',
    storageBucket: 'ecommerce-5ae51.firebasestorage.app',
    iosBundleId: 'com.example.adminapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6RaR1l1bJIjEt6fpDw4hJCqvEKHfAyfA',
    appId: '1:836519579068:web:3cae302087a1d5729fafb9',
    messagingSenderId: '836519579068',
    projectId: 'ecommerce-5ae51',
    authDomain: 'ecommerce-5ae51.firebaseapp.com',
    storageBucket: 'ecommerce-5ae51.firebasestorage.app',
  );
}